### ISSUE TITLE
fairshake.cloud DNS record

### ISSUE THREAD

**Issue by u8sand** [Nitrogen-DCPPC/FAIRshake#1]
Currently the `fairshake.cloud` domain name is a redirect to an another IP address.

fairshake.cloud: Registered as 50.63.202.7
Redirects to http://54.175.203.110/fairshake/

#### 1
The openapi spec is accessible here: <http://54.175.203.110/fairshake/static/openapi.json>
but not here: <http://fairshake.cloud/fairshake/static/openapi.json> which turns into <http://54.175.203.110/fairshake/fairshake/static/openapi.json>.

#### 2
`fairshake.cloud` redirects to an insecure version of the site. Passwords are thus completely unprotected from man-in-the-middle attacks. 

#### 3
Users who use the site see the IP address instead of the host name `fairshake.cloud` making URLs seemingly very suspicious.

### Therefore
I recommend that we register the `fairshake.cloud` as an A record with the actual server's IP address instead of a redirect.

**Comment by AviMaayan** [comment]
This is now fixed on GoDaddy but the index page needs to be moved to the root.
