### ISSUE TITLE
Question 8 & 9 - wrong reference in Harmonizome

### ISSUE THREAD

**Issue by jzhao6** [Nitrogen-DCPPC/FAIRshake#11]
Question 8 asked about API and question 9 asked about Terms, however the example links are flipped in order.
 i.e.
8. The tool can be accessed programmatically through an API and follows community standards for open APIs.
http://amp.pharm.mssm.edu/Harmonizome/terms
Rouillard AD, Gundersen GW, Fernandez NF, Wang Z, Monteiro CD, McDermott MG, Ma'ayan A. The harmonizome: a collection of processed datasets gathered to serve and mine knowledge about genes and proteins. Database (Oxford). 2016 Jul 3;2016. pii: baw100.

**Comment by lw453** [comment]
Changed example answer for Question 8.
