### ISSUE TITLE
Project analytics fail to load properly if an assessment for an associated digital object is started but not submitted.

### ISSUE THREAD

**Issue by alexjones1725** [Nitrogen-DCPPC/FAIRshake#110]
Plots 1,3,4 all show 'Not enough information was present to construct a plot.' in this situation.

**Comment by u8sand** [comment]
Nice catch; hope this didn't cause you trouble during your presentation. We
should be a able to fix it by making the plots drop nans.

**Comment by alexjones1725** [comment]
I was able to use a different project for the presentation, but was just something I noticed during prep. Thanks!
