### ISSUE TITLE
Default answers could be more specific

### ISSUE THREAD

**Issue by maxim-k** [Nitrogen-DCPPC/FAIRshake#12]
For example, URL is suggested as an example answer for Question 9 (about license). Question itself says 'on a home page' so it will be a home page URL. Would it make more sense to input license type (e.g. GPL license v3) instead of URL?

Same applies to Question 7 (contact info). It will be nice to have Name, E-mail, Affiliation fields

**Comment by u8sand** [comment]
I believe this may be outside of the scope of FAIR assessments--the goal is not to build a database of information for Digital Objects but rather assert that the information could indeed be found.
