### ISSUE TITLE
Make the Chrome extension insignia available from the following sites

### ISSUE THREAD

**Issue by AviMaayan** [Nitrogen-DCPPC/FAIRshake#2]
All assets from these sites: 

- [ ] https://www.gtexportal.org/home/
- [ ] https://wormbase.org
- [ ] https://zfin.org/
- [ ] http://www.informatics.jax.org/
- [ ] http://flybase.org/
- [ ] https://rgd.mcw.edu/
- [ ] https://www.yeastgenome.org/

**Comment by u8sand** [comment]
What's the status of this issue?
