### ISSUE TITLE
Change footer to reflect KC1 teams

### ISSUE THREAD

**Issue by u8sand** [Nitrogen-DCPPC/FAIRshake#22]

**Comment by u8sand** [comment]
Was this done already, if not, what should the footer be instead?

**Comment by AviMaayan** [comment]
No. It was not done yet. It should be changed to this for now:

Team Nitrogen, KC1, DCPPC
Ma'ayan Laboratory of Computational Systems Biology
Icahn School of Medicine at Mount Sinai
