### ISSUE TITLE
Perform FAIRness evaluations to all assets from these sites

### ISSUE THREAD

**Issue by AviMaayan** [Nitrogen-DCPPC/FAIRshake#3]
All assets from these sites: 

- [x] https://www.gtexportal.org/home/
  https://fairshake.cloud/v2/digital_object/569/ 
- [x] https://wormbase.org
  https://fairshake.cloud/v2/digital_object/413/
- [x] https://zfin.org/
  https://fairshake.cloud/v2/digital_object/427/
- [x] http://www.informatics.jax.org/
  https://fairshake.cloud/v2/digital_object/431/
- [x] http://flybase.org/
  https://fairshake.cloud/v2/digital_object/412/
- [x] https://rgd.mcw.edu/
  https://fairshake.cloud/v2/digital_object/655/
- [x] https://www.yeastgenome.org/
  https://fairshake.cloud/v2/?q=https%3A%2F%2Fwww.yeastgenome.org%2F

**Comment by u8sand** [comment]
Was this done already as part of the deliverable?

**Comment by Drosophilic** [comment]
If completed, it would be good to link to the actual evaluations here.
