### ISSUE TITLE
Enable users to delete their accounts (and authored objects?)

### ISSUE THREAD

**Issue by u8sand** [Nitrogen-DCPPC/FAIRshake#34]

**Comment by u8sand** [comment]
Do we delete user contributions when they delete their account? Or keep their contributions?

**Comment by Drosophilic** [comment]
Just my two cents - I would say you always keep their contributions, but transfer them to a holding 'deleted user' account (assuming all contributions need to be associated with a user account).

**Comment by u8sand** [comment]
The running idea is to delete things that have one and only author (the one and only author being the person who created it).
