### ISSUE TITLE
Is "Bring your own id" something we would want?

### ISSUE THREAD

**Issue by u8sand** [Nitrogen-DCPPC/FAIRshake#37]
On one hand, we could evaluate digital objects even if they weren't registered yet with FAIRshake, on the other hand, it would not promote filling in metadata about digital objects for use on the FAIRshake site. Is it possible that this metadata could simply be derived from assessments of another rubric?

**Comment by Drosophilic** [comment]
IMHO, I think this could get very messy very quickly. I would suggest we offer a select number of common identifiers e.g. DOI, PURL, LSID...

**Comment by u8sand** [comment]
Thanks for chiming in, this is precisely why I created this issue.

Currently, we are requiring that digital objects be registered with FAIRshake--potentially at the time of assessment. While enabling the use of existing identifiers sounds promising, I fear there doesn't exist any real universal identifier and no information that can be derived from them in a common and consistent way.  It is certainly possible to enable an arbitrary sized list of alias identifiers but I would suggest *that* would certainly get messy but maybe a necessary evil that we could also leverage for our automated assessments.

The only identifier that I believe nears universality (albeit not always persistent) is a url--bonus points if that url is persistent i.e. the url pointing to a DOI or something. If only there was a way of mapping url to universal identifier. While sites which facilitate user assessments could forward that information, it wouldn't work on arbitrary sites which users visit. Maybe this is *good enough*

**Comment by Drosophilic** [comment]
I agree that a small list could get messy, and of course, users will complain that their ID schema of choice is not included but I worry that restricting solely to URL will create problems, particularly in terms of maintenance given their non-persistent nature. I'm sceptical about whether they are _good enough_ or not.

**Comment by u8sand** [comment]
This has basically been addressed--the answer was your ID should be encoded as a url which can resolve your id.
