### ISSUE TITLE
Ensure we can identify and merge duplicate objects

### ISSUE THREAD

**Issue by u8sand** [Nitrogen-DCPPC/FAIRshake#47]
- [ ] Potentially add a way for users to communicate with the authors of the duplicates to agree to resolve them and in what way. -> Moved to #60 
- [x] At least ensure we can do it administratively and allow users to report duplication

**Comment by AviMaayan** [comment]
I suggest assigning GUIDs to assessments and digital objects the moment an assessment was submitted... and somehow link these two and date stamp them...

**Comment by u8sand** [comment]
@AviMaayan I'm having a hard time finding resources for how I am supposed to be creating GUIDs.

I ultimately found these:
- https://ors.datacite.org/docs
- http://smart-api.info/ui/bf9abe9c17c9c78c432832382ef9e16a

Both have `doi` and `ark` but judging by the metadata requested, I'm unsure assessments *or* digital objects fit.

Assessments are already timestamped, and I can add version control throughout the entire database (for tracking **all** modifications), perhaps this is enough--I don't think we need attempt to assess older-than-today versions of a given digital object.

**Comment by AviMaayan** [comment]
Sounds good. We want to be able to follow the change in FAIRness overtime... If we issue GUIDs to the digital objects in FAIRshake, this may cause more confusion...


Best,


Avi


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Avi Ma’ayan, PhD
Professor, Department of Pharmacological Sciences
Director, Mount Sinai Center for Bioinformatics
Icahn School of Medicine at Mount Sinai
New York, NY 10029
(212) 241-1153
Lab: http://www.mssm.edu/labs/maayan
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
________________________________
