### ISSUE TITLE
Assessments from FAIRshake Jam needs to be imported into FAIRshake

### ISSUE THREAD

**Issue by AviMaayan** [Nitrogen-DCPPC/FAIRshake#55]
These need to be added to the tools project, or better yet, create a new project called "FAIRshake Jam for Bioinformatics Tools 2018"

**Comment by u8sand** [comment]
I think it might make sense just to make a Jam tab, given that we have Request Assessments support--a FAIRshakeJam-like interface can be used to deal with those requests.

**Comment by AviMaayan** [comment]
Sounds good. We plan to have more jams in phase 2...

**Comment by u8sand** [comment]
Did this in 76de431d71a7504ba0bfe6db5738fa8e70ea76a0 --still need to resolve and consolidate duplicates and orphans before they will be visible on the homepage (#47)
