### ISSUE TITLE
Clicking FAIRness of GTEx Tools and Datasets under Projects makes you stay on that page

### ISSUE THREAD

**Issue by AviMaayan** [Nitrogen-DCPPC/FAIRshake#56]
FAIRness of GTEx Tools and Datasets

**Comment by u8sand** [comment]
This is because these projects don't have proper urls assigned. What URL should I put for them?

**Comment by AviMaayan** [comment]
It should just go here: https://fairshake.cloud/project/11/

**Comment by AviMaayan** [comment]
The same for the other projects... It is ok that the logo takes you to the same place, but the logo should probably take you to the original site... For example:
GTEx https://gtexportal.org/home/
AGR https://www.alliancegenome.org/
LINCS http://lincsproject.org/
Datasets2Tools http://amp.pharm.mssm.edu/datasets2tools/
DataMed https://datamed.org/
FAIRsharing https://fairsharing.org/
