### ISSUE TITLE
Move affiliations from footer to partners page

### ISSUE THREAD

**Issue by u8sand** [Nitrogen-DCPPC/FAIRshake#62]
Include logos from many other partners who make this project possible

**Comment by u8sand** [comment]
https://fairshake.cloud/affiliations/

**Comment by AviMaayan** [comment]
Can you please add this... https://lpi.oregonstate.edu/faculty-staff/melissa-haendel

**Comment by AviMaayan** [comment]
Change Affiliations to Contributors and Partners
