### ISSUE TITLE
Tested the Chrome Extension on ZFIN and it did not work

### ISSUE THREAD

**Issue by AviMaayan** [Nitrogen-DCPPC/FAIRshake#63]
Removed the FAIRshake Chrome extension
Install the FAIRshake Chrome extension from the Chrome Store
Visited the site https://zfin.org/
Clicked on the extension icon
Link to FAIRshake did not work - expected behavior is that it would take me to FAIRshake
Insignia is showing in gray - expected behavior is to see evaluation regardless if I am signed in
Submit evaluation took me to a site on FAIRshake that says Server Error - expected to be routed to a login page or an evaluation form, or a place to request to become an evaluator.
Logged in to FAIRshake using GitHub - Behavior did not change
This is ZFIN entry on FAIRshake https://fairshake.cloud/digital_object/427/

**Comment by u8sand** [comment]
The insignia via both the chrome extension and bookmarklet show up for me on `http://zfin.org` but not on `https://zfin.org`. Maybe i'll remove the protocol from url matching.

The evaluation submission is pending completion of #46--the chrome extension uses the *not-yet-established* assessment url.
