### ISSUE TITLE
Please don't store passwords in plain text

### ISSUE THREAD

**Issue by amalic** [Nitrogen-DCPPC/FAIRshake#79]
see: https://github.com/Nitrogen-DCPPC/FAIRshake/blob/15a9e1f95becaed49e2a06836ed05d8206a50a2c/scripts/db.py#L151

This [Stackoverflow Thread](https://stackoverflow.com/questions/2572099/pythons-safest-method-to-store-and-retrieve-passwords-from-a-database) could be helpful.

**Comment by u8sand** [comment]
This is a database conversion script. That model is for the original prototype, we only store password hashes.
